#Configuracion de Fernanpop
#Sun Apr 26 19:07:42 CEST 2026
acceso.invitado=false
data.file=data/fernanpop.dat
ultima.sesion.ana_at_fernanpop_com=26/04/2026 19\:07\:42
ultima.sesion.nachescalpro_at_gmail_com=26/04/2026 16\:32\:54
